#spring:
#  security:
#    user:
#      name: user
#      password: user

spring:
  datasource:
    url: jdbc:mysql://192.168.31.132:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xxd
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      pool-name: MyHikariCP
      connection-timeout: 30000
      connection-test-query: select 1
mybatis:
  mapper-locations: classpath*:/mapper/*.xml