server:
  port: 40004

dubbo:
  protocol:
    name: dubbo
    port: 50004
  application:
    id: seckill-gateway
    name: seckill-gateway
  registry:
    address: nacos://nacos.server:8848
  consumer:
    check: false
    filter: traceFilter
  provider:
    filter: traceFilter