server:
  port: 40001


spring:
  datasource:
    url: jdbc:mysql://192.168.31.132:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xxd
  data:
    redis:
      repositories:
        enabled: true

  redis:
    host: 192.168.31.132
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: -1

dubbo:
  registry:
    address: nacos://nacos.server:8848
  application:
    name: seckill-support-launcher
  protocol:
    port: 50001
    name: dubbo
  consumer:
    check: false
#    filter: trace
#  provider:
#    filter: trace
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
