spring:
  redis:
    lettuce:
      pool:
        min-idle: 5
        max-active: 10
      shutdown-timeout: 100ms
    host: 192.168.31.132
    database: 2
  cache:
    redis:
      key-prefix: oauth-
